-- Taskly Supabase/PostgreSQL schema
create extension if not exists pgcrypto;

create table public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  name text not null,
  email text not null,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.workspaces (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  owner_profile_id bigint references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.workspace_members (
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner','admin','member','guest')),
  is_active boolean not null default true,
  joined_at timestamptz not null default now(),
  primary key (workspace_id, profile_id)
);
create index workspace_members_user_idx on public.workspace_members(user_id, is_active);

create table public.clients (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  name text not null,
  colour text not null default '#64748B',
  icon text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(workspace_id, name)
);

create table public.channels (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  client_id bigint references public.clients(id) on delete set null,
  name text not null,
  type text not null default 'team' check (type in ('team','project','direct')),
  icon text,
  is_archived boolean not null default false,
  created_by_profile_id bigint references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workspace_id, name)
);

create table public.channel_members (
  channel_id bigint not null references public.channels(id) on delete cascade,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_read_at timestamptz,
  primary key(channel_id, profile_id)
);

create table public.messages (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  channel_id bigint not null references public.channels(id) on delete cascade,
  sender_profile_id bigint not null references public.profiles(id),
  body text not null,
  type text not null default 'text' check(type in ('text','voice','system')),
  client_mutation_id uuid unique,
  reply_to_message_id bigint references public.messages(id) on delete set null,
  edited_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz not null default now()
);
create index messages_channel_created_idx on public.messages(channel_id, created_at);

create table public.tasks (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  client_id bigint references public.clients(id) on delete set null,
  channel_id bigint references public.channels(id) on delete set null,
  source_message_id bigint references public.messages(id) on delete set null,
  creator_profile_id bigint not null references public.profiles(id),
  assignee_id bigint references public.profiles(id) on delete set null,
  title text not null,
  description text,
  status text not null default 'todo' check(status in ('todo','in-progress','done')),
  priority text not null default 'medium' check(priority in ('low','medium','high')),
  deadline timestamptz,
  position numeric(18,6) not null default 0,
  source_type text not null default 'manual' check(source_type in ('manual','message','voice')),
  origin_text text,
  reminder_enabled boolean not null default false,
  version integer not null default 1,
  client_mutation_id uuid unique,
  completed_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index tasks_workspace_status_idx on public.tasks(workspace_id,status,deadline);
create index tasks_assignee_idx on public.tasks(assignee_id,status);

create table public.subtasks (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  title text not null,
  is_done boolean not null default false,
  position integer not null default 0,
  version integer not null default 1,
  client_mutation_id uuid unique,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.task_comments (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  profile_id bigint not null references public.profiles(id),
  body text not null,
  client_mutation_id uuid unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.task_status_histories (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  changed_by_profile_id bigint references public.profiles(id),
  from_status text,
  to_status text not null,
  created_at timestamptz not null default now()
);

create table public.tags (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique(workspace_id,name)
);
create table public.task_tags (
  task_id bigint not null references public.tasks(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key(task_id,tag_id)
);

create table public.attachments (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete cascade,
  message_id bigint references public.messages(id) on delete cascade,
  uploaded_by_profile_id bigint not null references public.profiles(id),
  bucket text not null default 'task-files',
  path text not null unique,
  original_name text not null,
  mime_type text,
  size_bytes bigint,
  created_at timestamptz not null default now(),
  check ((task_id is not null)::int + (message_id is not null)::int = 1)
);

create table public.task_suggestions (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  message_id bigint not null unique references public.messages(id) on delete cascade,
  assignee_id bigint references public.profiles(id),
  title text not null,
  deadline timestamptz,
  priority text not null default 'medium' check(priority in ('low','medium','high')),
  status text not null default 'pending' check(status in ('pending','confirmed','dismissed')),
  confirmed_task_id bigint references public.tasks(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.reminders (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  task_id bigint not null references public.tasks(id) on delete cascade,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  remind_at timestamptz not null,
  status text not null default 'pending' check(status in ('pending','sent','cancelled')),
  created_at timestamptz not null default now()
);

create table public.device_tokens (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  platform text not null check(platform in ('android','ios','web')),
  token text not null unique,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create or replace function public.current_profile_id() returns bigint
language sql stable security definer set search_path=public as $$
  select id from public.profiles where auth_user_id = auth.uid() limit 1
$$;

create or replace function public.is_workspace_member(p_workspace_id bigint) returns boolean
language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.workspace_members where workspace_id=p_workspace_id and user_id=auth.uid() and is_active=true)
$$;

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path=public as $$
declare p_id bigint; w_id bigint; w_name text; w_slug text;
begin
  insert into public.profiles(auth_user_id,name,email)
  values(new.id, coalesce(new.raw_user_meta_data->>'name', split_part(new.email,'@',1)), new.email)
  returning id into p_id;
  w_name := coalesce(nullif(new.raw_user_meta_data->>'workspace_name',''), 'My Workspace');
  w_slug := lower(regexp_replace(w_name,'[^a-zA-Z0-9]+','-','g')) || '-' || substr(new.id::text,1,8);
  insert into public.workspaces(name,slug,owner_profile_id) values(w_name,w_slug,p_id) returning id into w_id;
  insert into public.workspace_members(workspace_id,profile_id,user_id,role) values(w_id,p_id,new.id,'owner');
  insert into public.clients(workspace_id,name,colour,icon) values(w_id,'Internal','#64748B','🏠');
  insert into public.channels(workspace_id,name,type,icon,created_by_profile_id) values(w_id,'Team General','team','💬',p_id);
  return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.record_task_status_change() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  if old.status is distinct from new.status then
    insert into public.task_status_histories(task_id,changed_by_profile_id,from_status,to_status)
    values(new.id,public.current_profile_id(),old.status,new.status);
    new.completed_at := case when new.status='done' then now() else null end;
  end if;
  new.updated_at := now();
  return new;
end $$;
create trigger task_status_change before update on public.tasks for each row execute function public.record_task_status_change();

create or replace function public.detect_task_suggestion(p_message_id bigint) returns bigint
language plpgsql security definer set search_path=public as $$
declare m public.messages; mentioned text; assignee bigint; task_title text; suggestion_id bigint;
begin
  select * into m from public.messages where id=p_message_id and public.is_workspace_member(workspace_id);
  if not found then return null; end if;
  mentioned := substring(m.body from '@([A-Za-z0-9_]+)');
  if mentioned is null then return null; end if;
  select p.id into assignee from public.profiles p join public.workspace_members wm on wm.profile_id=p.id
   where wm.workspace_id=m.workspace_id and lower(split_part(p.name,' ',1))=lower(mentioned) limit 1;
  if assignee is null then return null; end if;
  task_title := trim(regexp_replace(regexp_replace(m.body,'@[A-Za-z0-9_]+','','g'),'(complete|finish|do|send|update|fix|create|prepare|make|write|review)',' ','gi'));
  if length(task_title)<2 then task_title := 'New Task'; end if;
  insert into public.task_suggestions(workspace_id,message_id,assignee_id,title)
  values(m.workspace_id,m.id,assignee,initcap(task_title)) on conflict(message_id) do update set title=excluded.title
  returning id into suggestion_id;
  return suggestion_id;
end $$;

create or replace function public.confirm_task_suggestion(p_suggestion_id bigint) returns bigint
language plpgsql security definer set search_path=public as $$
declare s public.task_suggestions; m public.messages; t_id bigint;
begin
  select * into s from public.task_suggestions where id=p_suggestion_id and public.is_workspace_member(workspace_id) for update;
  if not found then raise exception 'Suggestion not found'; end if;
  if s.confirmed_task_id is not null then return s.confirmed_task_id; end if;
  select * into m from public.messages where id=s.message_id;
  insert into public.tasks(workspace_id,channel_id,source_message_id,creator_profile_id,assignee_id,title,deadline,priority,source_type,origin_text,client_mutation_id)
  values(s.workspace_id,m.channel_id,m.id,public.current_profile_id(),s.assignee_id,s.title,s.deadline,s.priority,'message',m.body,gen_random_uuid()) returning id into t_id;
  update public.task_suggestions set status='confirmed',confirmed_task_id=t_id,updated_at=now() where id=s.id;
  return t_id;
end $$;

alter table public.profiles enable row level security;
alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;
alter table public.clients enable row level security;
alter table public.channels enable row level security;
alter table public.channel_members enable row level security;
alter table public.messages enable row level security;
alter table public.tasks enable row level security;
alter table public.subtasks enable row level security;
alter table public.task_comments enable row level security;
alter table public.task_status_histories enable row level security;
alter table public.tags enable row level security;
alter table public.task_tags enable row level security;
alter table public.attachments enable row level security;
alter table public.task_suggestions enable row level security;
alter table public.reminders enable row level security;
alter table public.device_tokens enable row level security;

create policy profiles_read_workspace on public.profiles for select using (
  id=public.current_profile_id() or exists(select 1 from public.workspace_members mine join public.workspace_members theirs on theirs.workspace_id=mine.workspace_id where mine.user_id=auth.uid() and mine.is_active and theirs.profile_id=profiles.id)
);
create policy profiles_update_self on public.profiles for update using(auth_user_id=auth.uid()) with check(auth_user_id=auth.uid());
create policy workspace_member_access on public.workspaces for select using(public.is_workspace_member(id));
create policy workspace_members_access on public.workspace_members for select using(public.is_workspace_member(workspace_id));

create policy clients_all_members on public.clients for all using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));
create policy channels_all_members on public.channels for all using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));
create policy channel_members_access on public.channel_members for all using(exists(select 1 from public.channels c where c.id=channel_id and public.is_workspace_member(c.workspace_id))) with check(exists(select 1 from public.channels c where c.id=channel_id and public.is_workspace_member(c.workspace_id)));
create policy messages_all_members on public.messages for all using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id) and sender_profile_id=public.current_profile_id());
create policy tasks_all_members on public.tasks for all using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));
create policy subtasks_all_members on public.subtasks for all using(exists(select 1 from public.tasks t where t.id=task_id and public.is_workspace_member(t.workspace_id))) with check(exists(select 1 from public.tasks t where t.id=task_id and public.is_workspace_member(t.workspace_id)));
create policy comments_all_members on public.task_comments for all using(exists(select 1 from public.tasks t where t.id=task_id and public.is_workspace_member(t.workspace_id))) with check(profile_id=public.current_profile_id() and exists(select 1 from public.tasks t where t.id=task_id and public.is_workspace_member(t.workspace_id)));
create policy history_read_members on public.task_status_histories for select using(exists(select 1 from public.tasks t where t.id=task_id and public.is_workspace_member(t.workspace_id)));
create policy tags_all_members on public.tags for all using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));
create policy task_tags_all_members on public.task_tags for all using(exists(select 1 from public.tasks t where t.id=task_id and public.is_workspace_member(t.workspace_id))) with check(exists(select 1 from public.tasks t where t.id=task_id and public.is_workspace_member(t.workspace_id)));
create policy attachments_all_members on public.attachments for all using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id) and uploaded_by_profile_id=public.current_profile_id());
create policy suggestions_all_members on public.task_suggestions for all using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));
create policy reminders_own on public.reminders for all using(profile_id=public.current_profile_id()) with check(profile_id=public.current_profile_id());
create policy device_tokens_own on public.device_tokens for all using(profile_id=public.current_profile_id()) with check(profile_id=public.current_profile_id());

insert into storage.buckets(id,name,public,file_size_limit) values('task-files','task-files',false,26214400) on conflict(id) do nothing;
create policy task_files_read on storage.objects for select using(bucket_id='task-files' and public.is_workspace_member(split_part(name,'/',1)::bigint));
create policy task_files_insert on storage.objects for insert with check(bucket_id='task-files' and public.is_workspace_member(split_part(name,'/',1)::bigint));
create policy task_files_delete on storage.objects for delete using(bucket_id='task-files' and public.is_workspace_member(split_part(name,'/',1)::bigint));

alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.tasks;
