-- Taskly v6.3 - local-first chat + one-device account gate
-- This migration NEVER purges public.messages automatically.
-- Chat bodies/media are local on the device; the server may retain only the
-- existing short-lived encrypted delivery envelopes required for delivery.

begin;

create table if not exists public.taskly_primary_devices_v61 (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  device_id text not null,
  device_name text,
  platform text,
  is_primary boolean not null default true,
  is_active boolean not null default true,
  registered_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  replaced_at timestamptz,
  unique(profile_id, device_id)
);

create unique index if not exists taskly_primary_devices_v61_one_primary_idx
  on public.taskly_primary_devices_v61(profile_id)
  where is_primary=true and is_active=true;

alter table public.taskly_primary_devices_v61 enable row level security;
drop policy if exists taskly_primary_devices_v61_select_own on public.taskly_primary_devices_v61;
create policy taskly_primary_devices_v61_select_own
on public.taskly_primary_devices_v61 for select to authenticated
using (profile_id=public.current_profile_id());
revoke insert, update, delete on public.taskly_primary_devices_v61 from authenticated;
grant select on public.taskly_primary_devices_v61 to authenticated;

create table if not exists public.taskly_chat_migration_devices_v63 (
  profile_id bigint primary key references public.profiles(id) on delete cascade,
  device_id text not null,
  message_count bigint not null default 0,
  completed_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

alter table public.taskly_chat_migration_devices_v63 enable row level security;
drop policy if exists taskly_chat_migration_devices_v63_select_own on public.taskly_chat_migration_devices_v63;
create policy taskly_chat_migration_devices_v63_select_own
on public.taskly_chat_migration_devices_v63 for select to authenticated
using (profile_id=public.current_profile_id());

revoke insert, update, delete on public.taskly_chat_migration_devices_v63 from authenticated;
grant select on public.taskly_chat_migration_devices_v63 to authenticated;

-- The obsolete client-side removed-attachment list must never be rendered.
do $$
declare r record;
begin
  for r in select table_name from information_schema.tables
    where table_schema='public' and table_name in (
      'removed_attachments','deleted_attachments','attachment_tombstones','removed_message_attachments'
    )
  loop
    execute format('delete from public.%I', r.table_name);
  end loop;
end;
$$;

-- Replace the earlier v6.1 replacement behavior. A second device is blocked;
-- the existing device is never silently logged out or replaced.
create or replace function public.taskly_register_primary_device_v63(
  p_device_id text,
  p_device_name text default null,
  p_platform text default null
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_profile bigint := public.current_profile_id();
  v_existing text;
  v_known boolean := false;
begin
  if v_profile is null then raise exception 'No Taskly profile for this account'; end if;
  if nullif(trim(coalesce(p_device_id,'')),'') is null then raise exception 'device_id is required'; end if;
  perform pg_advisory_xact_lock(v_profile);

  select device_id into v_existing
  from public.taskly_primary_devices_v61
  where profile_id=v_profile and is_primary=true and is_active=true
  order by last_seen_at desc
  limit 1;

  select exists(
    select 1 from public.taskly_primary_devices_v61
    where profile_id=v_profile and device_id=p_device_id
  ) into v_known;

  if v_existing is not null and v_existing <> p_device_id then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'already_connected',
      'device_id', p_device_id,
      'existing_device_id', v_existing,
      'message', 'This account is already connected to another device. Chat backup and device switching are coming soon.'
    );
  end if;

  insert into public.taskly_primary_devices_v61(
    profile_id,device_id,device_name,platform,is_primary,is_active,
    registered_at,last_seen_at,replaced_at
  ) values(
    v_profile,p_device_id,nullif(trim(p_device_name),''),nullif(trim(p_platform),''),
    true,true,now(),now(),null
  )
  on conflict(profile_id,device_id) do update set
    device_name=excluded.device_name,
    platform=excluded.platform,
    is_primary=true,
    is_active=true,
    last_seen_at=now(),
    replaced_at=null;

  return jsonb_build_object(
    'allowed', true,
    'device_id', p_device_id,
    'is_new_device', not v_known
  );
end;
$$;

create or replace function public.taskly_touch_primary_device_v63(p_device_id text)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  update public.taskly_primary_devices_v61
  set last_seen_at=now()
  where profile_id=public.current_profile_id()
    and device_id=p_device_id
    and is_primary=true and is_active=true;
end;
$$;

grant execute on function public.taskly_register_primary_device_v63(text,text,text) to authenticated;
grant execute on function public.taskly_touch_primary_device_v63(text) to authenticated;

create or replace function public.taskly_ack_chat_local_migration_v63(p_message_count bigint default 0)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_profile bigint := public.current_profile_id();
  v_device text;
begin
  if v_profile is null then raise exception 'No Taskly profile'; end if;
  select device_id into v_device
  from public.taskly_primary_devices_v61
  where profile_id=v_profile and is_primary=true and is_active=true
  limit 1;
  if v_device is null then raise exception 'No active Taskly device'; end if;

  insert into public.taskly_chat_migration_devices_v63(profile_id,device_id,message_count,completed_at,last_seen_at)
  values(v_profile,v_device,greatest(coalesce(p_message_count,0),0),now(),now())
  on conflict(profile_id) do update set
    device_id=excluded.device_id,
    message_count=excluded.message_count,
    completed_at=excluded.completed_at,
    last_seen_at=excluded.last_seen_at;

  return jsonb_build_object('acknowledged',true,'device_id',v_device,'message_count',greatest(coalesce(p_message_count,0),0));
end;
$$;

grant execute on function public.taskly_ack_chat_local_migration_v63(bigint) to authenticated;

create or replace function public.taskly_chat_purge_readiness_v63()
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_required bigint;
  v_ready bigint;
begin
  select count(distinct profile_id) into v_required
  from public.taskly_primary_devices_v61
  where is_primary=true and is_active=true;
  select count(*) into v_ready
  from public.taskly_chat_migration_devices_v63 m
  where exists (
    select 1 from public.taskly_primary_devices_v61 d
    where d.profile_id=m.profile_id and d.device_id=m.device_id
      and d.is_primary=true and d.is_active=true
  );
  return jsonb_build_object(
    'ready', v_required > 0 and v_ready >= v_required,
    'required', v_required,
    'ready_devices', v_ready
  );
end;
$$;

revoke all on function public.taskly_chat_purge_readiness_v63() from public;

-- Final purge is intentionally explicit. It can only run when every profile
-- that currently has an active primary device has acknowledged migration.
-- This protects an offline phone from losing its last cloud copy before it has
-- had a chance to migrate.
create or replace function public.taskly_finalize_local_chat_purge_v63()
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_required bigint;
  r record;
  v_ready bigint;
  v_messages bigint := 0;
begin
  select count(distinct profile_id) into v_required
  from public.taskly_primary_devices_v61
  where is_primary=true and is_active=true;

  -- An acknowledgement is valid only if the device copied at least the
  -- complete message set visible to that profile. This prevents an empty or
  -- partial local database from authorising a destructive purge.
  select count(*) into v_ready
  from public.taskly_chat_migration_devices_v63 m
  join public.taskly_primary_devices_v61 d
    on d.profile_id=m.profile_id
   and d.device_id=m.device_id
   and d.is_primary=true
   and d.is_active=true
  where m.message_count >= coalesce((
    select count(*)
    from public.messages msg
    join public.channel_members cm
      on cm.channel_id=msg.channel_id
     and cm.profile_id=m.profile_id
  ),0);

  if v_required=0 or v_ready < v_required then
    return jsonb_build_object('purged',false,'reason','devices_not_migrated','required',v_required,'ready',v_ready);
  end if;

  if to_regclass('public.messages') is not null then
    execute 'select count(*) from public.messages' into v_messages;
  end if;

  -- Delete message-derived children first. These are permanent chat state,
  -- not task data, and are removed only after every active device is ready.
  for r in
    select table_name, column_name
    from information_schema.columns
    where table_schema='public'
      and column_name='message_id'
      and table_name <> 'messages'
  loop
    execute format('delete from public.%I where message_id is not null', r.table_name);
  end loop;

  if to_regclass('public.attachments') is not null and exists(
    select 1 from information_schema.columns
    where table_schema='public' and table_name='attachments' and column_name='message_id'
  ) then
    execute 'delete from public.attachments where message_id is not null';
  end if;

  if to_regclass('public.messages') is not null then
    execute 'delete from public.messages';
  end if;

  for r in select table_name from information_schema.tables
    where table_schema='public' and table_name in (
      'task_ai_feedback','task_ai_decisions','task_ai_runs','task_ai_jobs_v30','task_ai_user_aliases',
      'removed_attachments','deleted_attachments','attachment_tombstones','removed_message_attachments'
    )
  loop
    execute format('delete from public.%I', r.table_name);
  end loop;

  if to_regclass('public.notifications') is not null and exists(
    select 1 from information_schema.columns
    where table_schema='public' and table_name='notifications' and column_name='type'
  ) then
    execute $q$delete from public.notifications where lower(coalesce(type,'')) in ('message','chat_message','new_message','mention')$q$;
  end if;

  return jsonb_build_object('purged',true,'messages_deleted',v_messages,'devices',v_ready);
end;
$$;

revoke execute on function public.taskly_finalize_local_chat_purge_v63() from authenticated;

-- No message body/attachment purge occurs here.

commit;
