-- Taskly v4.0: mobile notifications, safe sharing, forwarded messages,
-- contact cards and user-involved task visibility.
-- Idempotent: safe to run once after the existing v3.2/v3.3 AI migration.

create extension if not exists pgcrypto;

alter table public.messages
  add column if not exists attachment_bucket text,
  add column if not exists attachment_path text,
  add column if not exists attachment_name text,
  add column if not exists attachment_mime_type text,
  add column if not exists attachment_size_bytes bigint,
  add column if not exists mentioned_profile_ids bigint[] not null default '{}',
  add column if not exists is_pinned boolean not null default false,
  add column if not exists forwarded_from_message_id bigint references public.messages(id) on delete set null,
  add column if not exists shared_contact_profile_id bigint references public.profiles(id) on delete set null,
  add column if not exists shared_contact_name text,
  add column if not exists shared_contact_phone text,
  add column if not exists shared_contact_email text;

-- Widen only the message-type check so new message cards remain valid.
do $$
declare constraint_name text;
begin
  for constraint_name in
    select con.conname
    from pg_constraint con
    where con.conrelid = 'public.messages'::regclass
      and con.contype = 'c'
      and pg_get_constraintdef(con.oid) ilike '%type%'
  loop
    execute format('alter table public.messages drop constraint if exists %I', constraint_name);
  end loop;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.messages'::regclass
      and conname = 'messages_type_v40_check'
  ) then
    alter table public.messages add constraint messages_type_v40_check
      check (type in ('text','voice','system','file','image','contact'));
  end if;
end $$;

create index if not exists messages_forwarded_from_idx
  on public.messages(forwarded_from_message_id)
  where forwarded_from_message_id is not null;

create table if not exists public.message_reactions (
  message_id bigint not null references public.messages(id) on delete cascade,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  emoji text not null check (char_length(emoji) between 1 and 16),
  created_at timestamptz not null default now(),
  primary key(message_id, profile_id, emoji)
);
alter table public.message_reactions enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='message_reactions' and policyname='message_reactions_member_v40') then
    create policy message_reactions_member_v40 on public.message_reactions for all
      using (exists (
        select 1 from public.messages m
        where m.id=message_id and public.is_workspace_member(m.workspace_id)
      ))
      with check (
        profile_id=public.current_profile_id() and exists (
          select 1 from public.messages m
          where m.id=message_id and public.is_workspace_member(m.workspace_id)
        )
      );
  end if;
end $$;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  actor_profile_id bigint references public.profiles(id) on delete set null,
  workspace_id bigint references public.workspaces(id) on delete cascade,
  channel_id bigint references public.channels(id) on delete cascade,
  message_id bigint references public.messages(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete cascade,
  type text not null default 'message',
  title text not null,
  body text not null default '',
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.notifications
  add column if not exists actor_profile_id bigint references public.profiles(id) on delete set null,
  add column if not exists workspace_id bigint references public.workspaces(id) on delete cascade,
  add column if not exists channel_id bigint references public.channels(id) on delete cascade,
  add column if not exists message_id bigint references public.messages(id) on delete cascade,
  add column if not exists task_id bigint references public.tasks(id) on delete cascade,
  add column if not exists type text not null default 'system',
  add column if not exists title text not null default 'Taskly',
  add column if not exists body text not null default '',
  add column if not exists is_read boolean not null default false,
  add column if not exists created_at timestamptz not null default now();
-- Existing installations may already use additional notification categories.
-- Remove restrictive type checks and keep the column as text so chat notifications
-- can be added without invalidating older rows.
do $$
declare constraint_name text;
begin
  for constraint_name in
    select con.conname
    from pg_constraint con
    where con.conrelid = 'public.notifications'::regclass
      and con.contype = 'c'
      and pg_get_constraintdef(con.oid) ilike '%type%'
  loop
    execute format('alter table public.notifications drop constraint if exists %I', constraint_name);
  end loop;
end $$;
create index if not exists notifications_profile_created_v40_idx
  on public.notifications(profile_id, created_at desc);
create unique index if not exists notifications_message_recipient_v40_uidx
  on public.notifications(profile_id, message_id)
  where message_id is not null;

-- In-app notification rows are created inside the database transaction, so a
-- temporary client or FCM failure never loses the notification badge/history.
create or replace function public.taskly_create_message_notifications_v40()
returns trigger language plpgsql security definer set search_path=public as $$
declare
  v_sender_name text;
  v_channel_name text;
  v_channel_type text;
  v_title text;
  v_preview text;
begin
  select p.name into v_sender_name from public.profiles p where p.id=new.sender_profile_id;
  select c.name,c.type into v_channel_name,v_channel_type from public.channels c where c.id=new.channel_id;
  v_title := case when v_channel_type='direct'
    then coalesce(v_sender_name,'Taskly user')
    else coalesce(v_sender_name,'Taskly user') || ' · ' || coalesce(v_channel_name,'Taskly')
  end;
  v_preview := case
    when new.type='contact' then 'Contact: ' || coalesce(new.shared_contact_name,new.body,'Shared contact')
    when new.type='image' then '📷 Photo'
    when nullif(new.attachment_name,'') is not null then '📎 ' || new.attachment_name
    else left(coalesce(nullif(trim(new.body),''),'New message'),180)
  end;

  insert into public.notifications(
    profile_id,actor_profile_id,workspace_id,channel_id,message_id,
    type,title,body,is_read
  )
  select cm.profile_id,new.sender_profile_id,new.workspace_id,new.channel_id,new.id,
         'message',v_title,v_preview,false
  from public.channel_members cm
  where cm.channel_id=new.channel_id
    and cm.profile_id<>new.sender_profile_id
    and not exists (
      select 1 from public.notifications n
      where n.profile_id=cm.profile_id and n.message_id=new.id
    );
  return new;
end $$;

drop trigger if exists taskly_message_notifications_v40 on public.messages;
create trigger taskly_message_notifications_v40
after insert on public.messages
for each row execute function public.taskly_create_message_notifications_v40();

alter table public.notifications enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='notifications' and policyname='notifications_read_own_v40') then
    create policy notifications_read_own_v40 on public.notifications for select
      using (profile_id=public.current_profile_id());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='notifications' and policyname='notifications_update_own_v40') then
    create policy notifications_update_own_v40 on public.notifications for update
      using (profile_id=public.current_profile_id())
      with check (profile_id=public.current_profile_id());
  end if;
end $$;

alter table public.device_tokens
  add column if not exists device_id text,
  add column if not exists is_enabled boolean not null default true,
  add column if not exists updated_at timestamptz not null default now();
create index if not exists device_tokens_profile_enabled_v40_idx
  on public.device_tokens(profile_id, is_enabled);
create unique index if not exists device_tokens_profile_device_v40_uidx
  on public.device_tokens(profile_id, device_id)
  where device_id is not null;

create or replace function public.taskly_register_device_token_v40(
  p_token text,
  p_platform text,
  p_device_id text
) returns void
language plpgsql security definer set search_path=public as $$
declare v_profile bigint := public.current_profile_id();
begin
  if v_profile is null then raise exception 'Not authenticated'; end if;
  if p_platform not in ('android','ios','web') then raise exception 'Invalid platform'; end if;
  if length(trim(p_token)) < 20 or length(trim(p_device_id)) < 8 then raise exception 'Invalid device registration'; end if;

  delete from public.device_tokens
   where token=trim(p_token) and profile_id<>v_profile;

  insert into public.device_tokens(profile_id,platform,token,device_id,is_enabled,last_seen_at,updated_at)
  values(v_profile,p_platform,trim(p_token),trim(p_device_id),true,now(),now())
  on conflict(token) do update set
    profile_id=excluded.profile_id,
    platform=excluded.platform,
    device_id=excluded.device_id,
    is_enabled=true,
    last_seen_at=now(),
    updated_at=now();
end $$;

grant execute on function public.taskly_register_device_token_v40(text,text,text) to authenticated;

create or replace function public.taskly_unregister_device_token_v40(p_token text)
returns void language sql security definer set search_path=public as $$
  delete from public.device_tokens
  where profile_id=public.current_profile_id() and token=p_token
$$;
grant execute on function public.taskly_unregister_device_token_v40(text) to authenticated;

create or replace function public.taskly_set_push_enabled_v40(p_enabled boolean)
returns void language sql security definer set search_path=public as $$
  update public.device_tokens set is_enabled=p_enabled, updated_at=now()
  where profile_id=public.current_profile_id()
$$;
grant execute on function public.taskly_set_push_enabled_v40(boolean) to authenticated;

create or replace function public.taskly_visible_task_ids_v40()
returns table(task_id bigint)
language sql stable security definer set search_path=public as $$
  with me as (select public.current_profile_id() id)
  select distinct t.id
  from public.tasks t, me
  where t.deleted_at is null
    and (
      t.assignee_id=me.id
      or t.creator_profile_id=me.id
      or exists (
        select 1 from public.channel_members cm
        where cm.channel_id=t.channel_id and cm.profile_id=me.id
      )
    )
$$;
grant execute on function public.taskly_visible_task_ids_v40() to authenticated;

-- Enforce the same task visibility at the database boundary, not only in Flutter.
drop policy if exists tasks_all_members on public.tasks;
drop policy if exists tasks_select_involved_v40 on public.tasks;
drop policy if exists tasks_insert_member_v40 on public.tasks;
drop policy if exists tasks_update_involved_v40 on public.tasks;
drop policy if exists tasks_delete_involved_v40 on public.tasks;

create policy tasks_select_involved_v40 on public.tasks for select
using (
  public.is_workspace_member(workspace_id)
  and (
    assignee_id=public.current_profile_id()
    or creator_profile_id=public.current_profile_id()
    or exists (
      select 1 from public.channel_members cm
      where cm.channel_id=tasks.channel_id
        and cm.profile_id=public.current_profile_id()
    )
  )
);

create policy tasks_insert_member_v40 on public.tasks for insert
with check (
  public.is_workspace_member(workspace_id)
  and creator_profile_id=public.current_profile_id()
  and (
    channel_id is null
    or exists (
      select 1 from public.channel_members cm
      where cm.channel_id=tasks.channel_id
        and cm.profile_id=public.current_profile_id()
    )
  )
);

create policy tasks_update_involved_v40 on public.tasks for update
using (
  public.is_workspace_member(workspace_id)
  and (
    assignee_id=public.current_profile_id()
    or creator_profile_id=public.current_profile_id()
    or exists (
      select 1 from public.channel_members cm
      where cm.channel_id=tasks.channel_id
        and cm.profile_id=public.current_profile_id()
    )
  )
)
with check (public.is_workspace_member(workspace_id));

create policy tasks_delete_involved_v40 on public.tasks for delete
using (
  public.is_workspace_member(workspace_id)
  and (
    creator_profile_id=public.current_profile_id()
    or exists (
      select 1 from public.channel_members cm
      where cm.channel_id=tasks.channel_id
        and cm.profile_id=public.current_profile_id()
    )
  )
);

create or replace function public.taskly_channel_messages_v40(p_channel_id bigint)
returns jsonb
language plpgsql stable security definer set search_path=public as $$
declare
  v_profile bigint := public.current_profile_id();
  v_workspace bigint;
  v_result jsonb;
begin
  select c.workspace_id into v_workspace from public.channels c where c.id=p_channel_id;
  if v_workspace is null or not public.is_workspace_member(v_workspace) then
    raise exception 'Conversation unavailable';
  end if;
  if exists(select 1 from public.channel_members where channel_id=p_channel_id)
     and not exists(select 1 from public.channel_members where channel_id=p_channel_id and profile_id=v_profile) then
    raise exception 'Not a conversation member';
  end if;

  select coalesce(jsonb_agg(item order by (item->>'created_at')::timestamptz),'[]'::jsonb)
  into v_result
  from (
    select jsonb_build_object(
      'id',m.id,'workspace_id',m.workspace_id,'channel_id',m.channel_id,
      'body',m.body,'type',m.type,'created_at',m.created_at,
      'edited_at',m.edited_at,'deleted_at',m.deleted_at,
      'mentioned_profile_ids',coalesce(m.mentioned_profile_ids,'{}'::bigint[]),
      'attachment_bucket',m.attachment_bucket,'attachment_path',m.attachment_path,
      'attachment_name',m.attachment_name,'attachment_mime_type',m.attachment_mime_type,
      'attachment_size_bytes',m.attachment_size_bytes,'is_pinned',m.is_pinned,
      'reply_to_message_id',m.reply_to_message_id,
      'forwarded_from_message_id',m.forwarded_from_message_id,
      'shared_contact_profile_id',m.shared_contact_profile_id,
      'shared_contact_name',m.shared_contact_name,
      'shared_contact_phone',m.shared_contact_phone,
      'shared_contact_email',m.shared_contact_email,
      'sender',jsonb_build_object(
        'id',sender.id,'name',sender.name,'email',sender.email,'phone',sender.phone,
        'phone_country_iso',sender.phone_country_iso,'avatar_url',sender.avatar_url,'about',sender.about
      ),
      'reply_to',case when reply.id is null then null else jsonb_build_object(
        'id',reply.id,'body',reply.body,'type',reply.type,'created_at',reply.created_at,
        'deleted_at',reply.deleted_at,
        'sender',jsonb_build_object('id',reply_sender.id,'name',reply_sender.name,'email',reply_sender.email)
      ) end,
      'message_reactions',coalesce((
        select jsonb_agg(jsonb_build_object('emoji',mr.emoji,'profile_id',mr.profile_id))
        from public.message_reactions mr where mr.message_id=m.id
      ),'[]'::jsonb),
      'suggestion',case when ts.id is null then null else jsonb_build_object(
        'id',ts.id,'title',ts.title,'description',ts.description,'deadline',ts.deadline,
        'priority',ts.priority,'status',ts.status,'confidence',ts.confidence,
        'action_type',ts.action_type,'target_task_id',ts.target_task_id,'ai_reason',ts.ai_reason,
        'assignee',case when assignee.id is null then null else jsonb_build_object(
          'id',assignee.id,'name',assignee.name,'email',assignee.email,'phone',assignee.phone,
          'avatar_url',assignee.avatar_url,'about',assignee.about
        ) end
      ) end
    ) item
    from (
      select * from public.messages
      where channel_id=p_channel_id
      order by created_at desc
      limit 250
    ) m
    join public.profiles sender on sender.id=m.sender_profile_id
    left join public.messages reply on reply.id=m.reply_to_message_id
    left join public.profiles reply_sender on reply_sender.id=reply.sender_profile_id
    left join public.task_suggestions ts on ts.message_id=m.id
    left join public.profiles assignee on assignee.id=ts.assignee_id
  ) q;
  return v_result;
end $$;
grant execute on function public.taskly_channel_messages_v40(bigint) to authenticated;

create or replace function public.taskly_mark_notification_read(p_notification_id bigint)
returns void language sql security definer set search_path=public as $$
  update public.notifications set is_read=true
  where id=p_notification_id and profile_id=public.current_profile_id()
$$;
create or replace function public.taskly_mark_all_notifications_read()
returns void language sql security definer set search_path=public as $$
  update public.notifications set is_read=true
  where profile_id=public.current_profile_id() and not is_read
$$;
grant execute on function public.taskly_mark_notification_read(bigint) to authenticated;
grant execute on function public.taskly_mark_all_notifications_read() to authenticated;

-- Realtime is used for chat cards and in-app notification badges.
do $$ begin
  begin alter publication supabase_realtime add table public.notifications; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.message_reactions; exception when duplicate_object then null; end;
end $$;
